{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Default name'|i18n( 'design/standard/class/datatype' )}:</label>
{if $class_attribute.data_text1}
    <p>{$class_attribute.data_text1|wash}</p>
{else}
    <p><i>{'Empty'|i18n( 'design/standard/class/datatype' )}</i></p>
{/if}
</div>
<div class="block">
    <label>{'Default type'|i18n( 'design/standard/class/datatype' )}:</label>
	{switch match=$class_attribute.data_text2}
		{case match="1"}
			{'Checkbox'|i18n( 'design/standard/class/datatype' )}
		{/case}
		{case match="2"}
			{'Drop-down list'|i18n( 'design/standard/class/datatype' )}
		{/case}
		{case}
			{'Radio'|i18n( 'design/standard/class/datatype' )}
		{/case}
	{/switch}
</div>
<div class="block">
    <label>{'Default required value'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_text3|choose( 'Unchecked'|i18n( 'design/standard/class/datatype' ), 'Checked'|i18n( 'design/standard/class/datatype' ) )}</p>
</div>

{* Default number of rows. *}
<div class="block">
    <label>{'Default number of rows'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int1}</p>
</div>

{* Columns. *}
<div class="block">
<label>{'Columns'|i18n( 'design/standard/class/datatype' )}:</label>
{section show=$class_attribute.content.columns}
<table class="list" cellspacing="0">
<tr>
    <th>{'Matrix column'|i18n( 'design/standard/class/datatype' )}</th>
    <th>{'Identifier'|i18n( 'design/standard/class/datatype' )}</th>
</tr>
{section var=Columns loop=$class_attribute.content.columns sequence=array( bglight, bgdark )}
<tr class="{$Columns.sequence}">
    <td>{$Columns.item.name|wash}</td>
    <td>{$Columns.item.identifier|wash}</td>
</tr>
{/section}
</table>
{section-else}
<p>
{'The matrix does not have any columns.'|i18n( 'design/standard/class/datatype' )}
</p>
{/section}
</div>
