{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<label>{$attribute.content.name}</label>

<label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}ContentClass-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_type">{'Type'|i18n( 'design/standard/content/datatype' )}:</label>
{$attribute.content.type_value|choose('Radio'|i18n( 'design/standard/class/datatype' ),'Checkbox'|i18n( 'design/standard/class/datatype' ),'Drop-down list'|i18n( 'design/standard/class/datatype' ) )}

<label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_required">{'Required'|i18n( 'design/standard/class/datatype' )}:</label>
{$attribute.content.required_value|choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}

{let matrix=$attribute.content}
<table class="list" cellspacing="0">
<tr>
{section var=ColumnNames loop=$matrix.columns.sequential}
<th>{$ColumnNames.item.name}</th>
{/section}
</tr>
{section var=Rows loop=$matrix.rows.sequential sequence=array( bglight, bgdark )}
<tr class="{$Rows.sequence}">
    {section var=Columns loop=$Rows.item.columns}
    <td>{$Columns.item|wash( xhtml )}</td>
    {/section}
</tr>
{/section}
</table>
{/let}
